# Helm values documentation: https://github.com/jbossas/eap-charts/tree/eap8/charts/eap8

build:
  env:
    - name: POSTGRESQL_DRIVER_VERSION
      value: "42.7.3"
    - name: POSTGRESQL_ENABLED
      value: "true"
  uri: https://github.com/atarazana/kitchensink.git     
  ref: eap-8.0                                  
  contextDir: .
deploy:
  labels:
    app.kubernetes.io/part-of: kitchensink-app
    app: kitchensink-app
  replicas: 2
  livenessProbe:
    httpGet:
      path: /health/live
      port: admin
    initialDelaySeconds: 0
    periodSeconds: 3
  readinessProbe:
    httpGet:
      path: /health/ready
      port: admin
    initialDelaySeconds: 1
    periodSeconds: 3
  startupProbe:
    httpGet:
      path: /health/live
      port: admin
    initialDelaySeconds: 5
    periodSeconds: 1
  env:
    - name: POSTGRESQL_DATASOURCE
      value: "kitchensink"
    - name: POSTGRESQL_DATABASE
      value: "kitchensink"
    - name: POSTGRESQL_USER
      value: "luke"
    - name: POSTGRESQL_PASSWORD
      value: "secret"
    - name: POSTGRESQL_HOST
      value: "kitchensink-db"
    - name: JGROUPS_PING_PROTOCOL
      value: "dns.DNS_PING"
    # - name: OPENSHIFT_DNS_PING_SERVICE_NAME
    #   value: "kitchensink-ping"
    # - name: OPENSHIFT_DNS_PING_SERVICE_PORT
    #   value: "8888"
    # - name: JGROUPS_CLUSTER
    #   value: "kitchensink-cluster"
    - name: JGROUPS_CLUSTER_PASSWORD
      value: "secret"