# Helm values documentation: https://github.com/jbossas/eap-charts/tree/eap8/charts/eap8

build:
  env:
    - name: POSTGRESQL_DRIVER_VERSION
      value: "42.7.3"
    - name: POSTGRESQL_ENABLED
      value: "true"
  uri: https://github.com/atarazana/kitchensink.git     
  ref: eap-8.0                                  
  contextDir: .
deploy:
  replicas: 1
  livenessProbe:
    httpGet:
      path: /health/live
      port: admin
    initialDelaySeconds: 0
    periodSeconds: 3
  readinessProbe:
    httpGet:
      path: /health/ready
      port: admin
    initialDelaySeconds: 1
    periodSeconds: 3
  startupProbe:
    httpGet:
      path: /health/live
      port: admin
    initialDelaySeconds: 5
    periodSeconds: 1
  env:
    - name: POSTGRESQL_DATASOURCE
      value: "kitchensink"
    - name: POSTGRESQL_DATABASE
      value: "kitchensink"
    - name: POSTGRESQL_USER
      value: "luke"
    - name: POSTGRESQL_PASSWORD
      value: "secret"
    - name: POSTGRESQL_HOST
      value: "kitchensink-db"