apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: argocd

resources:
- kitchensink-bc.yaml
- kitchensink-db-deployment.yaml
- kitchensink-db-svc.yaml
- kitchensink-dc.yaml
- kitchensink-is.yaml
- kitchensink-route.yaml
- kitchensink-svc.yaml